GET http://127.0.0.1:8000/api/v1/courses/
Content-Type: application/json

############

POST http://127.0.0.1:8000/api/v1/courses/
Content-Type: application/json

{
    "title": "teste token 1",
    "url": "https://www.apitokentest.com"
}

############

GET http://127.0.0.1:8000/api/v1/evaluations/
Content-Type: application/json

############

POST http://127.0.0.1:8000/api/v1/evaluations/
Content-Type: application/json

{
    "title": "teste token 1",
    "url": "https://www.apitokentest.com"
}

############

POST http://127.0.0.1:8000/test_token/
Content-Type: application/json

{}
